version: "3.9"
services:
  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
  server:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`server.docker.localhost`)"
    container_name: server
    build: .
    ports:
      - "3000:3000"
  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro,delegated
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"