version: "3.9"
services:
  nginx:
    image: nginx
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

  mitmweb:
    image: mitmproxy/mitmproxy
    tty: true
    ports:
      - 3000:8080
      - 8081:8081
    command: mitmweb --set keep_host_header --web-host 0.0.0.0 --mode reverse:http://nginx/
    depends_on:
      - nginx
      
  server:
    expose: [3000]
    container_name: server
    build: .
    ports:
      - "3001:3000"