version: '3.9'
services:
  nginx:
    ports:
      - "3000:80"
    volumes:
      - d:\\saturn:/mount/chd
  mitmweb:
    ports:
      - 4000:8080
      - 8081:8081
  server:
    volumes:
      - .:/workspace:cached
      - d:\\saturn:/chd
    command: /bin/sh -c "while sleep 1000; do :; done"
 
