version: '3.9'
services:
  nginx:
    volumes:
      - d:\\chd:/mount/chd

  server:
    volumes:
      - .:/workspace:cached
      - d:\\chd:/chd
    command: /bin/sh -c "while sleep 1000; do :; done"
 
